var namespacecopads_1_1copads_1_1copadsexceptions =
[
    [ "CopadsError", "classcopads_1_1copads_1_1copadsexceptions_1_1_copads_error.html", null ],
    [ "DistanceError", "classcopads_1_1copads_1_1copadsexceptions_1_1_distance_error.html", null ],
    [ "DistanceInputSizeError", "classcopads_1_1copads_1_1copadsexceptions_1_1_distance_input_size_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_distance_input_size_error" ],
    [ "DistributionError", "classcopads_1_1copads_1_1copadsexceptions_1_1_distribution_error.html", null ],
    [ "DistributionFunctionError", "classcopads_1_1copads_1_1copadsexceptions_1_1_distribution_function_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_distribution_function_error" ],
    [ "DistributionParameterError", "classcopads_1_1copads_1_1copadsexceptions_1_1_distribution_parameter_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_distribution_parameter_error" ],
    [ "EdgeNotFoundError", "classcopads_1_1copads_1_1copadsexceptions_1_1_edge_not_found_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_edge_not_found_error" ],
    [ "FunctionParameterTypeError", "classcopads_1_1copads_1_1copadsexceptions_1_1_function_parameter_type_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_function_parameter_type_error" ],
    [ "FunctionParameterValueError", "classcopads_1_1copads_1_1copadsexceptions_1_1_function_parameter_value_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_function_parameter_value_error" ],
    [ "GraphEdgeSizeMismatchError", "classcopads_1_1copads_1_1copadsexceptions_1_1_graph_edge_size_mismatch_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_graph_edge_size_mismatch_error" ],
    [ "GraphError", "classcopads_1_1copads_1_1copadsexceptions_1_1_graph_error.html", null ],
    [ "GraphParameterError", "classcopads_1_1copads_1_1copadsexceptions_1_1_graph_parameter_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_graph_parameter_error" ],
    [ "MatrixError", "classcopads_1_1copads_1_1copadsexceptions_1_1_matrix_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_matrix_error" ],
    [ "MaxIterationsException", "classcopads_1_1copads_1_1copadsexceptions_1_1_max_iterations_exception.html", null ],
    [ "NormalDistributionTypeError", "classcopads_1_1copads_1_1copadsexceptions_1_1_normal_distribution_type_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_normal_distribution_type_error" ],
    [ "NotAdjacencyGraphMatrixError", "classcopads_1_1copads_1_1copadsexceptions_1_1_not_adjacency_graph_matrix_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_not_adjacency_graph_matrix_error" ],
    [ "ParallelArrayError", "classcopads_1_1copads_1_1copadsexceptions_1_1_parallel_array_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_parallel_array_error" ],
    [ "StatisticsError", "classcopads_1_1copads_1_1copadsexceptions_1_1_statistics_error.html", null ],
    [ "TreeError", "classcopads_1_1copads_1_1copadsexceptions_1_1_tree_error.html", null ],
    [ "TreeNodeTypeError", "classcopads_1_1copads_1_1copadsexceptions_1_1_tree_node_type_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_tree_node_type_error" ],
    [ "UnknownGraphMatrixError", "classcopads_1_1copads_1_1copadsexceptions_1_1_unknown_graph_matrix_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_unknown_graph_matrix_error" ],
    [ "VectorError", "classcopads_1_1copads_1_1copadsexceptions_1_1_vector_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_vector_error" ],
    [ "VertexNotFoundError", "classcopads_1_1copads_1_1copadsexceptions_1_1_vertex_not_found_error.html", "classcopads_1_1copads_1_1copadsexceptions_1_1_vertex_not_found_error" ]
];